[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
shield_dex_pg = "7xCZgNDZ6da6Rup5eztPfPxuVNwVuvRac3nQK9U5ggEg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/nguyenduytra/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
